json.id product.id
json.name product.name
json.price product.price
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total product.total
json.description product.description
json.supplier_id product.supplier_id
json.images product.images
json.categories product.categories
